### ISSUE TITLE
Panics on overflow

### ISSUE THREAD

**Issue by niklasf** [pacman82/atoi-rs#1]
Hi, I just stumbled on a problem with overflows. I was expecting:

```rust
assert_eq!(None, atoi::<u8>(b"256"));
```

Instead it panics in debug mode and wraps around in release mode. I am not sure how to fix this, since there do not seem to be generic traits that provide checked addition/multiplication.

**Comment by pacman82** [comment]
Tough. Would switching to `u32` and testing size afterwards do the trick for you?

**Comment by pacman82** [comment]
Can your use case be supported by choosing a larger type to read the value? Let's say you want to parse an u8:
```rust
if let Some(input) = atoi::<u32>(b"256"){
    if input > std::u8::Max as u32{
        // Deal with overflow
    }
}
```

If you are in doubt `u32` might also not be large enough, to hold the ... wait a moment ...

**Comment by pacman82** [comment]
... I just realised that we would only need to check for the overflow after adding the third digit (for `u8`) or the say the tenth digit (for `u32`). Every number of digits smaller won't overflow and every number larger than that is guaranteed to do so. This just might be reasonable cheap.

**Comment by pacman82** [comment]
Closing this issue. Users can now opt into overflow checking using the `checked` crate. This also allows to distinguish between an overflow and not finding a number.

```rust
extern crate atoi;
extern crate checked;

fn main() {
    let number = atoi::atoi::<checked::Checked<u8>>(b"256");
    println!("Result: {:?}", number);
}
```

Prints: `Result: Some("overflow")`.

**Comment by niklasf** [comment]
Looks good. Thanks
