### ISSUE TITLE
fail to parse negative number

### ISSUE THREAD

**Issue by photoszzt** [pacman82/atoi-rs#9]
```rust
atoi::<i64>(b"-123")
```
the above code returns None instead of Some(-123).

**Comment by photoszzt** [comment]
Oh, it's not supported.

**Comment by pacman82** [comment]
Maybe it should be, though 🤔

**Comment by TianyiShi2001** [comment]
I wish this could be supported.

**Comment by pacman82** [comment]
The next time I can squeeze in some Open Source work I'll add support. Probably first as a non breaking additional function, and then let's see how we take things from there.

**Comment by pacman82** [comment]
Parsing negative integers (and nonnegatives with + Sign) is now supported via `FromRadix10Signed` and `FromRadix10SignedChecked`.

Question is, if we should make this the "default" behaviour, by using `FromRadix10SignedChecked` in the `atoi` function instead of `FromRadix10Checked`?

**Comment by pacman82** [comment]
Parsing with support for signs is now the 'default'. Closing this issue.
